apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" . }}-server-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
    netbird-app: {{ include "netbird.fullname" . }}-server
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: {{ .Values.global.server.port }}
{{- if .Values.global.server.metrics.exposed }}
    - name: metrics
      targetPort: metrics
      protocol: TCP
      port: {{ .Values.global.server.metrics.port | default 9090 }}
{{- end }}
{{- if .Values.global.server.legacyGrpc.exposed }}
    - name: legacy-grpc
      targetPort: legacy-grpc
      protocol: TCP
      appProtocol: kubernetes.io/h2c
      port: {{ .Values.global.server.legacyGrpc.port | default 33073 }}
{{- end }}
  selector:
    {{- include "netbird.selectorLabels" . | nindent 4 }}
    netbird-app: {{ include "netbird.fullname" . }}-server
